### ISSUE TITLE
Option to hide the banner

### ISSUE THREAD

**Issue by hapklaar** [teeminus/NoTouchScreenFirmware#59]
Hi @teeminus 

The NoTouchFw v1.3.1 banner looks a bit strange on my TFT35B1. (It's compiled in normal mode, I don't like the stretched out Full Screen look.)

![image](https://user-images.githubusercontent.com/7703320/141118152-71fc16be-b045-452f-ab6c-5b18916b26a5.png)

- Is it some kind of display corruption, like I'm experiencing more often during printing? (https://github.com/teeminus/NoTouchScreenFirmware/issues/47)
- Is it possible to hide the banner or make an option to do so?

Edit: found out the 'corruption' is actually the SPI_DATA_RECEIVED_INDICATOR I enabled in features.h. Doesn't seem to show well on my display for some reason. I guess it should look like a dot?

**Comment by teeminus** [comment]
The spi activity indicator is working as intended. For each byte received a pixel on the left and right side of the top label is drawn/cleared. As the data is received in blobs one usually does not notice a single pixel of the indicator been drawn/cleared rather than complete lines of the indicator change.

This feature is for debugging purposes only, it is not required for normal operation.

**Comment by hapklaar** [comment]
Got it. Is it possible to hide the banner or make an option to do so?

**Comment by teeminus** [comment]
It sure is. However, hiding the header makes debugging more complicated. Even when the spi status indicator is not enabled, the header contains valuable information I can use to figure out what might be going wrong.

So adding an option to remove the header would make debugging for those builds more complicated.

It might sound a bit harsh (which is not intentional) but if you really don't like the header, you can easily remove it in your fork.
